rtabmap:
  ros__parameters:

    frame_id: "ascamera_hp60c_camera_link_0"
    odom_frame_id: "odom"
    map_frame_id: "map"

    subscribe_depth: true
    subscribe_odom_info: false
    publish_tf: true

    approx_sync: false

    'Mem/IncrementalMemory': true
    'Mem/InitWMWithAllNodes': false

    'Vis/MaxFeatures': 400
    'RGBD/LinearUpdate': 0.01
    'RGBD/AngularUpdate': 0.0